services:
  db:
    image: postgres:15-alpine
    container_name: drone_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shacio21
      POSTGRES_DB: auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:                                      # ← tambah ini
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend
    container_name: drone_backend
    restart: always
    env_file:
      - ./Backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy                    # ← ubah ini
    volumes:
      - ./Backend:/app

  frontend:
    build: ./frontend
    container_name: drone_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: